### ISSUE TITLE
Upload new version to jetbrains repo

### ISSUE THREAD

**Issue by jeremyherbert** [JesusFreke/fusionIdea#13]
Could you please push the new version including https://github.com/JesusFreke/fusionIdea/commit/8bfaf80e9190c2e82db42567d350b74b77576579 to the jetbrains repo? 

Thanks!

**Comment by JesusFreke** [comment]
Done, it'll be a couple of days before it's available. You can download it from https://github.com/JesusFreke/fusionIdea/releases/tag/v0.6.1 in the meantime.
