### ISSUE TITLE
Fail to load plugin descriptor from file fusion_idea-0.6.2.zip in PyCharm 2021.1.2

### ISSUE THREAD

**Issue by dlwh** [JesusFreke/fusionIdea#15]
I just get a popup that says "Fail to load plugin descriptor from file fusion_idea-0.6.2.zip" when I try to install the plugin in the most recent PyCharm 2021.1.2 I tried both from the plugin site and direct from the releases entry here. Running on Windows 10. I didn't try mac.

**Comment by JesusFreke** [comment]
Yep! It's a known issue with the new version. I've filed a bug here: https://youtrack.jetbrains.com/issue/IDEA-270963

I do have a workaround in mind that I can try though. I'll try and get a new release out soon.

**Comment by dlwh** [comment]
great thanks! i guess my google fu didn't find that.

**Comment by JesusFreke** [comment]
I've published a new v0.6.3 version to the plugin repository, but it usually takes a day or two to be approved. In the meantime, you can download the plugin at https://github.com/JesusFreke/fusionIdea/releases/tag/v0.6.3.

Give it a shot and see if it works for you.

**Comment by JesusFreke** [comment]
That was quick. It looks like it was already approved, and should be available in the plugin repository

**Comment by dlwh** [comment]
Thanks for being so responsive! I got it installed successfully. I haven't
yet tried anything beyond making sure it was actually there. Thanks for the
plugin!
