### ISSUE TITLE
Couldn't start ssdp server exception

### ISSUE THREAD

**Issue by SaugatPaudel** [JesusFreke/fusionIdea#19]
Hi, I was trying to setup fusion with pycharm. After installing I get the following error while trying to run the script.

"

AddIns/fusion_idea_addin/fusion_idea_addin.py", line 544, in server_bind
    raise Exception("Could not start ssdp server")
Exception: Could not start ssdp server

"

**Comment by JesusFreke** [comment]
Hi! Sorry about that, I think I've already fixed that issue, but I forgot to push the fix. I just pushed it and bumped the version to 1.5. Can you try the new version and see if that works for you?

**Comment by SaugatPaudel** [comment]
Working now. Thank you.
